INSERT INTO C_DEVICE_TYPE (ID, DESC) VALUES(0,"Sensor");
INSERT INTO C_DEVICE_TYPE (ID, DESC) VALUES(1,"Siren");
INSERT INTO C_DEVICE_TYPE (ID, DESC) VALUES(2,"Camera");

INSERT INTO C_POSITION(ID, FLOOR_LEVEL, DIST_FRONT_WALL, DIST_LEFT_WALL, DESC) VALUES (0, 0, 10,0,"Obyvaci pokoj");
INSERT INTO C_POSITION(ID, FLOOR_LEVEL, DIST_FRONT_WALL, DIST_LEFT_WALL, DESC) VALUES (1, 0, 5, 4,"Kuchyne");
INSERT INTO C_POSITION(ID, FLOOR_LEVEL, DIST_FRONT_WALL, DIST_LEFT_WALL, DESC) VALUES (2, 0, 2,5,"Chodba");

INSERT INTO C_DEVICE (ID, C_DEVICE_TYPE_ID, C_POSITION_ID, PIN, EXPANDER, DESC ) VALUES(0, 0, 0, 1,1,"Polohovy sensor obyvak");
INSERT INTO C_DEVICE (ID, C_DEVICE_TYPE_ID, C_POSITION_ID, PIN, EXPANDER, DESC ) VALUES(0, 1, 1, 2,1,"Sirena");
